"""Set default value of created_at

Revision ID: f4f0c23f0f6c
Revises: 6d6ccab44db3
Create Date: 2025-09-28 19:48:14.990072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision = 'f4f0c23f0f6c'
down_revision = '6d6ccab44db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###